name = "Eternal"
author = "Rinnray"
version = "4.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ddb41d1096cd0818472756d25815693dddcd06ab186b88876472eacd0e1568"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"

[options]
acceptable-game-versions = ["1.20"]
