name = "Eternal"
author = "Rinnray"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "086e1aadeed29c0ef65718889aa040e81d4aa8753291b46b337d8ded3221deef"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"

[options]
acceptable-game-versions = ["1.20"]
