name = "Eternal"
author = "Rinnray"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15e139752b2ef42cd9499e7b164452d78873237bafc49219a02e1f4f0ce3a767"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"

[options]
acceptable-game-versions = ["1.20"]
